[Feat] #21 - 마이페이지 UI 구현
PlanLit/PomoHabit pull request #24
Opened 2024-02-29 07:13 UTC by Lilyhly

##  작업한 내용

마이페이지 UI 구현

##  PR Point

마이페이지 UI 구현

## 스크린샷
![Simulator Screenshot - iPhone 15 Pro - 2024-02-29 at 16 11 46](https://github.com/PlanLit/PomoHabit/assets/149870768/d7407444-5099-4ad7-9e56-0bbddc4e01d6)

## 관련 이슈
extension label안에 코드
label.text = text 수정했음

- Resolved: #이슈번호

2024-02-29 09:39 UTC, dongjin97 reviewed
고생하셨습니다 ! 코드 깔끔하게 작성하셨는데 해당 코드로 UI캡슐화및 코드 컨벤션 참고해서 리팩토링 해주시면 좋을것 같습니다

2024-02-29 09:39 UTC, dongjin97 commented on PomoHabit/PomoHabit/Presentation/Mypage/Controllers/MypageViewController.swift
> +        myPageView.backgroundColor = .white
p2
해당 부분 함수화해서 선언하면 어떨까요 ?

2024-02-29 09:39 UTC, dongjin97 commented on PomoHabit/PomoHabit/Presentation/Mypage/Controllers/MypageViewController.swift
> +        }
p3
Button 쓰이는곳이 없는데 선언한 이유가 있을까요 ?

2024-02-29 09:39 UTC, dongjin97 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +}
p2
전체적으로 잘 정리해주셨는데 UI캡슐화 해주시고 UI 앞에 private lazy 붙여서 UI를 선언해주는게 좋을것같습니다.
lazy var 를 붙이는 이유는 let 선언시 해당 UI를 화면에 띄워주지 않는데 메모리를 잡게 되어 앱의 성능을 저하시킬수있기 때문입니다. 어제 튜터님이 이야기하신 부분인데요 레퍼런스 많이 존재하기 때문에 꼭 읽어 보시길 바랍니다.

저희 코드 컨벤션에서 addsubview와 오토레이아웃은 따로 함수로 만들어서 선언해주는 컨벤션도 지켜주면 좋겠습니다.
마찬가지로 코드컨벤션에서 extension활용해서 기능들을 나눈 부분 참고 해서 지켜주셨으면 좋겠습니다.

팀원 분들 View나 ViewController 참고하시면 도움이 될것 같습니다.

2024-02-29 09:39 UTC, dongjin97 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +
p3
공백 지워주세요!

2024-02-29 11:40 UTC, Lilyhly commented on PomoHabit/PomoHabit/Presentation/Mypage/Controllers/MypageViewController.swift
> +        }
지웠습니다!

2024-02-29 11:53 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Controllers/MypageViewController.swift
> +        myPageView.backgroundColor = .white
@Lilyhly 

p2;

loadView()에서 넣으면 addSubView랑 레이아웃 안잡아줘도 되요~

2024-02-29 11:55 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +    var myPageTableView: UITableView!
@Lilyhly 

p2;

강제 언래핑은 실패시 런타임 에러가 나기때문에 지양해주세요! 클로저 방식으로 초기화 시키면 쓰지 않아도 됩니다 ㅎㅎ

2024-02-29 11:59 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +        }
c;

아까 동진님이 말씀하신 부분인데 한 메서드가 너무 여러 일을 하고 있어요! 객체 지향 설계 측면에서 봤을 때 한 메서드가 너무 여러 일을 하면 좋지 않습니다 ㅎㅎ 저희 컨벤션처럼 분리해주세요!

2024-02-29 12:00 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +        }
해당 부분들도 메서드 하나가 너무 많은 일을 하고 있습니다 ㅎㅎ UI프로퍼티 부분에서 관리되어도 좋을 것 같네요. 다른 분들이 작성한 코드 많이 참고해서 리팩토링 해주세요~

2024-02-29 12:00 UTC, joonBaek12 reviewed
고생하셨습니다. 좀 더 힘내봐요~

2024-03-02 11:14 UTC, dongjin97 reviewed
리뷰사항 잘 반영했습니다. 반영안된 부분이 조금 있어서 수정하시면 좋을것같습니다. 
그리고 전체화면을 스크롤 되는게 좋을꺼같은데요 
UITableView의 Heaer안에 닉네임 View/UI와 습관 진행상태 VIew/UI에 넣는것도 좋을것같습니다.

2024-03-02 11:14 UTC, dongjin97 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +}
p3
setupConstraints 함수 내부안에 각 기능마다 한줄 띄워주세요!

2024-03-03 11:21 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Controllers/MypageViewController.swift
> +        setSetAutoLayout()
p2;

view = mypageView() 해주면 addSubview랑 autoLayout 안잡아도 됩니다 ㅎㅎ 
저는 개인적으로 rootView라는 변수명을 좋아하는데 추천드려요

2024-03-03 11:23 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +        }
c;

해당 부분들은 다 UIProperty들입니다. 저희 컨벤션 순서는

Properties

UI Properties

LifeCycle 메서드 순입니다. 기억해주세요!

2024-03-03 11:24 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +        self.addSubview(setupTotalAndDidDaysLabels)
p4;

UIView+Extension파일에 있는 addSubviews 메서드 사용해서 배열에 넣어주면 한줄로 작성할 수 있어요 ㅎㅎ

2024-03-03 11:26 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +            make.top.equalTo(safeAreaLayoutGuide.snp.top).offset(20)
p2;

nickNameLabel이랑 setupEditButton의 top이 같네요. 만약 디자이너가 두개의 값을 30으로 변경해달라고 했을 때, 이렇게 따로 잡으면 두번 변경해야하지만 setupEditButton의 top을 nickNameLabel에 맞춰준다면? nickNameLabel만 변경해주면 될겁니다 ㅎㅎ 이런식으로 재사용성을 고민하면서 레이아웃 잡아보시면 좋을 것 같아요~!

2024-03-03 11:27 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath) as! MyPageTableViewCell
c;

강제언래핑은 자제해주세요! 또한 cell이라고 직접 string값을 넣는것보다는 cell파일 내부에 static 변수를 만들어서 해당셀에서 불러와 사용하는 것이 휴먼에러를 조금이나마 방지할 수 있습니다.

2024-03-03 11:28 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/model/MypageModel.swift
> +import Foundation
q;

foundation 임포트가 꼭 필요한가요?!?

2024-03-04 02:32 UTC, Deferare requested changes

2024-03-04 07:51 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Controllers/MypageViewController.swift
> +        }
p1;

전에도 말씀드렸듯이 view = myPageRootView 해주면 잡아줄 필요 없어요

2024-03-04 07:53 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +    }()
q;

tableView 안에 있는 프로퍼티와 중복같은데 확인한번 부탁드릴게요~

2024-03-04 07:55 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +            make.trailing.equalToSuperview().offset(-70)
q;

여기는 왜 70인지 알 수 있을까요??

2024-03-04 07:56 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +            make.width.equalTo(390)
q;

grayBar의 leading.trailing은 equalToSuperView인데 여기에는 상수값이 들어간 이유는 무엇인가요?

2024-03-04 08:10 UTC, Lilyhly commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +            make.width.equalTo(390)
지웠습니다!

2024-03-04 08:11 UTC, Lilyhly commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +    }()
네 let tableView = UITableView(frame: .zero, style: .plain) 지웠습니다.

2024-03-04 08:11 UTC, Lilyhly commented on PomoHabit/PomoHabit/Presentation/Mypage/Controllers/MypageViewController.swift
> +        }
지웠습니다.

2024-03-04 08:51 UTC, Yu-RiChoi commented
수고하셨습니다 👍

2024-03-04 14:17 UTC, joonBaek12 commented on PomoHabit/PomoHabit/Presentation/Mypage/Views/MypageView.swift
> +            make.trailing.equalToSuperview().offset(-70)
아 다시 바꾸실 필요는 없구.. leading, trailing 둘 다 ovalView 기준으로 잡는건 어떠실까요

2024-03-05 11:05 UTC, dongjin97 approved these changes

2024-03-05 11:06 UTC, Deferare approved these changes

2024-03-05 11:22 UTC, closed without merging

2024-03-05 11:27 UTC, dongjin97 commented
develop branch에서 pull 받으신후 새로운 브랜치(feat/#21--MypageView) 생성후 #24  에 해당하는 기능및 리뷰사항 구현 (수정화면 개발중) -> feat/#21--MypageView는 develop에 merge 진행 후 해당 브랜치에서 수정화면 계속 개발 예정